# Generated by Django 5.0.4 on 2024-05-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flavour',
            field=models.CharField(default='', max_length=15),
        ),
    ]
