# Generated by Django 5.0.4 on 2024-05-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.CharField(choices=[('Recepcion', 'Recepcion'), ('Almacenado', 'Almacenado'), ('Envasado', 'Envasado'), ('Empaquetado', 'Empaquetado'), ('Calidad', 'Calidad'), ('Distribucion', 'Distribucion')], default='Recepcion', max_length=15),
        ),
    ]
