# Generated by Django 5.0.4 on 2024-05-09 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
    ]
