# Generated by Django 5.0.6 on 2024-05-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=25)),
                ('staff', models.CharField(default=False, max_length=10)),
            ],
        ),
    ]
