# Generated by Django 5.0.6 on 2024-05-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.CharField(max_length=10),
        ),
    ]
