# Generated by Django 5.0.6 on 2024-05-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='', max_length=25),
        ),
    ]
